name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: Auto Merge Dependabot PRs
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          # 限制合并条件，仅对 Dependabot PRs 生效
          mergeMethod: squash # 可选: merge, squash, rebase
          mergeFilterAuthor: "dependabot[bot],dependabot" # 限定作者为 Dependabot
          mergeFilterBranch: "" # 根据需要可以指定分支过滤
