name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the PR is from Dependabot
        uses: actions/github-script@v6
        with:
          script: |
            const prAuthor = context.payload.pull_request.user.login;
            if (prAuthor !== 'dependabot[bot]' && prAuthor !== 'dependabot') {
              core.setFailed('PR is not from Dependabot. Exiting...');
            }

      - name: Auto-merge PR
        uses: actions/merge-me-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash # 你可以用 'merge'、'squash' 或 'rebase'
