name: Build & Push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库
      uses: actions/checkout@v4

    - name: 设置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 安装依赖
      run: |
        npm install
        npm audit fix
        apt-get install rsync

    - name: Bulid Vitepress
      run: npm run build

    - name: Configure SSH keys
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.WXIES114514 }}

    - name: Push to server
      run: rsync -avz --delete docs/dist/* root@autopull.wxies.cn:/www/wwwroot/doc.wxies.cn/