name: Vitepress Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库
      uses: actions/checkout@v2

    - name: 设置 Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: 安装依赖
      run: npm install

    - name: 构建 Vitepress
      run: npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: 配置 SSH 密钥
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.WXIES114514 }}

    - name: 删除服务器上的旧文件
      run: ssh -o StrictHostKeyChecking=no root@43.153.178.35 'cd /www/wwwroot/doc.wxies.cn && rm -rf *'

    - name: 将构建输出推送到服务器
      run: scp -o StrictHostKeyChecking=no -r docs/dist/* root@43.153.178.35:/www/wwwroot/doc.wxies.cn/
